name: golangci-lint
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read # Use with `only-new-issues` option.
jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest 
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
